export const BLASTOISE_PARTICLE_PRESETS = Object.freeze({
    'water-channel': Object.freeze({
        particleClass: 'mega-channel',
        glyph: 'wave',
        color: '#b8f2ff',
        duration: 0.018,
        emissionRate: 300,
        totalParticles: 8,
        life: 0.24,
        lifeVar: 0.05,
        angleVar: 8,
        speed: 66,
        speedVar: 18,
        startSize: 9,
        startSizeVar: 2,
        tangentialAccel: 0,
        radialAccel: 0,
        gravityY: 0,
        posVar: 2,
    }),
    'water-impact': Object.freeze({
        particleClass: 'water-impact',
        glyph: 'wave',
        color: '#d9f8ff',
        duration: 0.018,
        emissionRate: 440,
        totalParticles: 11,
        life: 0.26,
        lifeVar: 0.05,
        angleVar: 164,
        speed: 82,
        speedVar: 32,
        startSize: 11,
        startSizeVar: 3,
        endSize: 1,
        tangentialAccel: 0,
        radialAccel: 18,
        gravityY: 0,
        posVar: 3,
    }),
});
