/** Player-facing release notes. Add the newest, concise entry here with every shipped update. */
export const UPDATE_LOG_ENTRIES = Object.freeze([
    {
        date: '2026-10-10',
        category: '神兽关卡',
        title: '固拉多加入陆之窟专属战场',
        description: '挑战固拉多时进入干燥岩土洞窟，岩壁围出有限的战斗区域，玩家可在中央空地自由走位。',
    },
    {
        date: '2026-10-10',
        category: '神兽关卡',
        title: '盖欧卡加入海之洞窟专属战场',
        description: '战斗切换到中央水池与环绕沙岸组成的有限场地；盖欧卡会沿水域巡游，并在招式预警时停下。',
    },
    {
        date: '2026-10-09',
        category: '战斗 HUD',
        title: 'BOSS 血条改为顶端紧凑显示',
        description: '修复训练家 BOSS 血条被挤出画面的问题；移除大信息窗、训练家与队伍名单、阶段文字和精灵头顶重复血条，只保留一条专属样式血条。',
    },
    {
        date: '2026-10-09',
        category: '神兽 HUD',
        title: '九只神兽改用专属无框能量血条',
        description: '以像素端饰和专属槽内纹样呈现九只神兽特征：凤王羽翼、烈空坐龙纹、盖欧卡鳍形等；凤王半血技能刻度保留。',
    },
    {
        date: '2026-10-08',
        category: '神兽关卡',
        title: '已解锁神兽地点可自由选择挑战',
        description: '不用先击败更早的神兽；靠近任一已解锁且未完成的地点即可进入，地点仍按训练家 BOSS 进度解锁。',
    },
    {
        date: '2026-10-08',
        category: '战斗音效',
        title: '裂空座出场加入云风音效',
        description: '进入裂空座的神兽出没地时播放云幕散开的短风掠声；静音测试参数照常生效。',
    },
    {
        date: '2026-10-08',
        category: '下载渠道',
        title: '首页新增 Windows EXE 与 Android APK 下载',
        description: '电脑端下载安装程序，Android 手机直接下载 APK；最新版安装包由 GitHub Releases 自动构建并更新。',
    },
    {
        date: '2026-10-07',
        category: 'MEGA视觉',
        title: '19 种 MEGA 加入专属像素描边',
        description: '按形态配色绘制贴合精灵轮廓的描边，加入呼吸亮度与少量上浮粒子，不使用圆环光晕。',
    },
    {
        date: '2026-10-07',
        category: 'MEGA视觉',
        title: '移除 MEGA 精灵身上的圆环光晕',
        description: '去掉 MEGA 泛光、常驻圆环和选中圆环，保留绕行的进化石，并用小菱形标出技能来源。',
    },
    {
        date: '2026-10-07',
        category: 'Mega技能',
        title: '喷火龙 X 苍焰十字加入实战',
        description: '喷火龙 X 升空蓄势后，在玩家选点引爆全屏渐尖蓝焰 X，再落地收势；命中判定、点燃/双扫斩/爆燃音效与演出同步。',
    },
    {
        date: '2026-10-07',
        category: '技能预览',
        title: '苍焰十字斩击带收窄',
        description: 'X 形火焰斩击带整体收窄约一半，保留全屏长度与交叉形态，命中范围不变。',
    },
    {
        date: '2026-10-07',
        category: '技能预览',
        title: '苍焰十字线条变得更有火焰流动感',
        description: '收弱硬朗描边，让 X 形蓝焰轮廓自然摆动、明暗起伏，边缘火舌改成弯曲渐尖的形状。',
    },
    {
        date: '2026-10-07',
        category: '技能预览',
        title: '苍焰十字音效减少金属感',
        description: '柔化火焰起音和扫斩的尖锐高频，降低叫声叠音，并让真实余烬噼啪声托住火焰尾音。',
    },
    {
        date: '2026-10-07',
        category: '技能预览',
        title: '苍焰十字恢复层叠火焰质感',
        description: '全屏 X 加回更密的锯齿焰缘、蓝青内焰与沿斩击流动的亮色火纹，避免拉长后纹理变稀。',
    },
    {
        date: '2026-10-07',
        category: '技能预览',
        title: '苍焰十字扩展到整个战场',
        description: '蓝焰 X 按玩家选点铺满整个战场；喷火龙 X 以更大体型高空升起，展开火翼后回落落地。',
    },
    {
        date: '2026-10-07',
        category: '技能预览',
        title: '喷火龙 X 飞升并扩大苍焰十字',
        description: '预览中喷火龙 X 会喷焰升空后发动更大范围的 X 形斩击，再落地收势；命中范围同步扩大。',
    },
    {
        date: '2026-10-07',
        category: '技能预览',
        title: '喷火龙 X 技能预览放大 X 形斩击',
        description: 'X 形火焰斩击加大约三成，并同步调整命中范围；预览保留三种火焰音效与喷火龙叫声。',
    },
    {
        date: '2026-10-07',
        category: '技能预览',
        title: '喷火龙 X 技能预览新增叫声与三种火焰音效',
        description: '三套火焰方案都加入喷火龙 X 的叫声，可在同一落点对比交叉爆燃、蓝焰疾掠和龙焰重击。',
    },
    {
        date: '2026-10-07',
        category: '技能预览',
        title: '喷火龙 X 蓝焰十字加入火焰音效',
        description: '加入火焰点燃、两段扫掠、爆燃与余烬噼啪声，让音效节奏贴合 X 形攻击演出。',
    },
    {
        date: '2026-10-06',
        category: '首页功能',
        title: '首页新增更新日志',
        description: '可查看近期游戏改动；之后的版本更新也会继续追加到这里。',
    },
    {
        date: '2026-10-06',
        category: '进化演出',
        title: 'BOSS奖励进化加入完整演出',
        description: '光效聚集后精灵升空、快速翻转，在白色剪影中完成形态变化，落地时恢复颜色。',
    },
    {
        date: '2026-10-06',
        category: '加载优化',
        title: '地图环境素材优先加载',
        description: '启动时先载入地面、树木和花草，让场景尽早完整显示；精灵图鉴素材继续后台加载。',
    },
    {
        date: '2026-10-06',
        category: '加载优化',
        title: '修复资源加载停滞',
        description: '为无响应的图片请求增加超时处理，避免游戏一直停在连接资源阶段。',
    },
    {
        date: '2026-10-06',
        category: '手机操作',
        title: '技能按钮支持拖动瞄准',
        description: '按住技能按钮拖动选择目标位置，松手释放；拖到范围外可取消。',
    },
    {
        date: '2026-10-06',
        category: '手机操作',
        title: '优化触屏移动与升级选择',
        description: '提高移动控制和升级卡片的触控响应，减少点选不灵敏的情况。',
    },
    {
        date: '2026-10-06',
        category: '道具与升级',
        title: '调整奇异糖果与升级选项',
        description: '奇异糖果使用对应道具图标并归入普通道具；移除调整丢球参数的升级选项。',
    },
    {
        date: '2026-10-06',
        category: 'MEGA进化',
        title: '加入MEGA光球与爆发演出',
        description: '紫色光球会完整包裹原精灵，再爆开发光并展示进化形态；MEGA演出使用独立音效。',
    },
    {
        date: '2026-10-06',
        category: '进化演出',
        title: '加快进化翻转并加入音效',
        description: '普通进化预览中的精灵翻转更利落，并加入来源音效。',
    },
]);
